apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-pod
    app: voting-app
spec:
  type: LoadBanalcer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: voting-pod
    app: voting-app